# This workflow executes the automerge python script to automatically merge
# changes from the `main` branch of upstream LLVM into the `qualcomm-software`
# branch of the sriyalamar/cpullvm-toolchain repository.
name: Automerge
on:
  workflow_run:
    workflows: [Sync from Upstream LLVM]
    types:
      - completed
  workflow_dispatch:
jobs:
  Run-Automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    if: github.repository == 'sriyalamar/cpullvm-toolchain'
    strategy:
      matrix:
        branches:
          - from_branch: main
            to_branch: qualcomm-software
    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.SYNC_APP_ID }}
          private-key: ${{ secrets.SYNC_APP_PRIVATE_KEY }}
      - name: Authenticate GitHub CLI
        run: |
          gh auth logout --hostname github.com || true
          echo "${{ steps.generate-token.outputs.token }}" | gh auth login --with-token
          gh auth setup-git
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branches.to_branch }}
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      - name: Configure Git Identity
        run: |
          git config --local user.name "Sri Lakshmi"
          git config --local user.email "syalamar@qti.qualcomm.com"
      - name: Fetch Branches
        run: |
          git remote set-branches --add origin ${{ matrix.branches.from_branch }}
          git fetch origin ${{ matrix.branches.from_branch }}:${{ matrix.branches.from_branch }}
          git pull --ff-only origin ${{ matrix.branches.to_branch }}
      - name: Run automerge
        run: python3 qualcomm-software/ci/automerge.py --project-name ${{ github.repository }} --from-branch ${{ matrix.branches.from_branch }} --to-branch ${{ matrix.branches.to_branch }} --verbose
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
