# Copyright (c) 2025, Arm Limited and affiliates.
# Part of the Arm Toolchain project, under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# ​​​​​Changes from Qualcomm Technologies, Inc. are provided under the following license:
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries. 
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Linux Premerge Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '.github/workflows/qcom-preflight-checks.yml'
      - '**/*.md'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    # Don't run on forks
    if: github.repository == 'qualcomm/cpullvm-toolchain'
    name: ${{ matrix.build_script }} on ${{ matrix.target_os }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - build_script: build.sh
            test_script: test.sh
            target_os: Linux-x86_64
            runner: self-hosted

          - build_script: build_musl-embedded_overlay.sh
            test_script: ''
            target_os: Linux-x86_64
            runner: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          # We build in the repository and rely on clean to cleanup possible
          # old build products if the runner doesn't do it itself.
          clean: true

      - name: Apply llvm-project patches
        run: python3 qualcomm-software/cmake/patch_repo.py --method apply qualcomm-software/patches/llvm-project

      - name: Build toolchain
        run: ./qualcomm-software/scripts/${{ matrix.build_script }}

      - name: Upload built packages
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: success()
        with:
          name: cpullvm-packages-${{ matrix.build_script }}-${{ matrix.target_os }}
          path: |
            build*/cpullvm-*.tar.xz
          retention-days: 1

      - name: Test
        if: matrix.test_script != ''
        run: ./qualcomm-software/scripts/${{ matrix.test_script }}
