name: Qualcomm Preflight Checks
on:
  # FIXME: these branch targets might need to be revisited to make this work
  # as we create new release branches.
  pull_request_target:
    branches:
      - 'qualcomm-software'
      - 'release/qualcomm-software/**'
  push:
    branches:
      - 'qualcomm-software'
      - 'release/qualcomm-software/**'
  workflow_dispatch:

permissions:
 contents: read
 security-events: write

jobs:
  qcom-preflight-checks:
    if: github.repository == 'qualcomm/cpullvm-toolchain'
    uses: qualcomm/qcom-reusable-workflows/.github/workflows/qcom-preflight-checks-reusable-workflow.yml@v1.1.4
    with:
        # ✅ Preflight Checkers
        repolinter: false                  # default: true
        semgrep: true                      # default: true
        copyright-license-detector: true   # default: true
        pr-check-emails: true              # default: true
        dependency-review: true            # default: true
    secrets:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
