# This workflow fetches changes from relevant branches from the
# llvm/llvm-project repository (upstream) into the corresponding branches
# in the qualcomm/cpullvm-toolchain repository (downstream), keeping them in sync.
name: Sync from Upstream LLVM
on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:
jobs:
  Fetch-Upstream:
    runs-on: ubuntu-24.04
    if: github.repository == 'qualcomm/cpullvm-toolchain'
    strategy:
      matrix:
        branch: [main]
    env:
      UPSTREAM_REMOTE: https://github.com/llvm/llvm-project.git
    steps:
      - name: Configure Access Token
        uses: actions/create-github-app-token@f45685208fd9b88321d74015b5996fc8c3e43d18 # v1.0.0
        id: generate-token
        with:
          app_id: ${{ secrets.SYNC_APP_ID }}
          private_key: ${{ secrets.SYNC_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ matrix.branch }}
          token: ${{ steps.generate-token.outputs.token }}
      - name: Configure Upstream Remote
        run: git remote add upstream ${{ env.UPSTREAM_REMOTE }}
      - name: Fetch Upstream Changes
        run: git pull --ff-only upstream ${{ matrix.branch }}
      - name: Configure Git Identity
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Push Changes
        run: git push origin ${{ matrix.branch }}
